# -*- coding: utf-8 -*-
#
# Copyright (C) 2019 CERN.
#
# inspirehep is free software; you can redistribute it and/or modify it under
# the terms of the MIT License; see LICENSE file for more details.

# addons:
#  chrome: stable # https://docs.travis-ci.com/user/chrome

sudo: true

dist: trusty

notifications:
  email: # sent to the committer and the author
    on_success: never
    on_failure: never

language: python

matrix:
  fast_finish: true

cache:
  - pip

services:
  - docker

env:
  global:
    - REQUIREMENTS=no
  matrix:
    - SUITE=integration EXTRAS=all,elasticsearch5,postgresql ES_VERSION=5.6.4
    - SUITE=unit

python:
  - "3.6"

before_install:
  - "sudo service postgresql stop"
  - if [ ${SUITE} == 'integration' ]; then docker-compose up -d; fi 
  - "travis_retry pip install --upgrade pip setuptools py pipenv"
  - "travis_retry pip install twine wheel coveralls"

install:
  - "./scripts/bootstrap --ci"

before_script:
  - if [ ${SUITE} == 'integration' ]; then ./docker/wait-for-services.sh; fi 

script:
  - if [ ${SUITE} == 'unit' ]; then ./run-tests.sh; fi 
  - if [ ${SUITE} == 'integration' ]; then pipenv run py.test tests/integration; fi 

after_success:
  - coveralls
