# -*- coding: utf-8 -*-
#
# Copyright (C) 2019 CERN.
#
# inspirehep is free software; you can redistribute it and/or modify it under
# the terms of the MIT License; see LICENSE file for more details.

addons:
  chrome: stable # https://docs.travis-ci.com/user/chrome

# Chrome Webdriver fails if not on sudo
# See https://github.com/travis-ci/travis-ci/issues/8836
sudo: true

dist: trusty # Chrome driver fails if not trusty dist

notifications:
  email: # sent to the committer and the author
    on_success: never # default: always
    on_failure: never # default: always

language: python

matrix:
  fast_finish: true

cache:
  - pip

services:
  - docker

env:
  global:
    - E2E=no
  matrix:
    - REQUIREMENTS=prod EXTRAS=all,elasticsearch5,postgresql ES_VERSION=5.6.4
    - REQUIREMENTS=qa EXTRAS=all,elasticsearch6,mysql ES_VERSION=5.6.4

python:
  - "3.6"

before_install:
  - "sudo service postgresql stop"
  - "docker-compose up -d"
  - "travis_retry pip install --upgrade pip setuptools py pipenv"
  - "travis_retry pip install twine wheel coveralls"

install:
  - "./scripts/bootstrap --ci"

before_script:
  - "./docker/wait-for-services.sh"

script:
  - ./run-tests.sh

after_success:
  - coveralls
